apiVersion: v1
kind: Service
metadata:
  name: {{ include "stackr.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stackr.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "stackr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
