apiVersion: v1
kind: Service
metadata:
  name: {{ include "stackr.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stackr.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "stackr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
