apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackr.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stackr.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
